// ../src/Frontend/Lexer.cpp generated by reflex 3.0.12 from Hyc.l

#define REFLEX_VERSION "3.0.12"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_header_file         "../include/Frontend/Lexer.h"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_outfile             "../src/Frontend/Lexer.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


#include "Token.h"
#include "DebugPrint.h"
#include "fmt/core.h"
#include <vector>
#include <algorithm>
#include <array>
#define PUSH(name) push(Token::Specifier::name)


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {

   std::vector<Token> m_tokens;
   size_t m_current_token = -1; // Start before the actual token
   std::string file;
   void push(Token::Specifier ttype)
   {
	m_tokens.emplace_back(ttype, str(), file, matcher().line(), lineno(), columno(), lineno_end(), columno_end());
   }

public:
   typedef size_t TokenPos;
   TokenPos get_tk_pos(){return m_current_token;}
   void goto_tk_pos(TokenPos tp) {m_current_token = tp;}
   void set_filename(const std::string& filename)
   {
        file=filename;
   }
   Token& eat()
   {
      Token& out = lookahead(1);
      m_current_token++;
      return out;
   }

   const Token& lookahead(size_t amount) const
   {
      auto minIndex = std::min(m_current_token+amount, m_tokens.size()-1);
      return m_tokens[minIndex];
   }

   bool is_at(Token::Specifier spec, size_t amount) const
   {
	return spec == lookahead(1).type;
   }

   Token& lookahead(size_t amount)
   {
       auto minIndex = std::min(m_current_token + amount, m_tokens.size() - 1);
       return m_tokens[minIndex];
   }

   Token& match_token(Token::Specifier type)
   {
      Token& token = eat();
      if(token.type != type)
      {
          auto descr = Error::FromToken(token);
          descr.Message = fmt::format("Expected {}, but got {}",Token::Translate(type),Token::Translate(token.type));
	  descr.Hint = fmt::format("The offending token is '{}'",token.text);
          Error::SyntacticalError(descr);
      }
      return token;
    }

template<Token::Specifier... specs>
   Token& match_one_of()
   {
       Token& token = eat();
       // One of the arguments is the token type
       if (((token.type == specs) || ... ))
       {
           return token;
       }
       else
       {
           std::array<Token::Specifier, sizeof... (specs)> specs_ary = { specs... };
           std::string exp = "";
           for (auto& spec : specs_ary)
           {
               exp += fmt::format("{}, ", Token::Translate(spec));
           }
           auto descr = Error::FromToken(token);
           descr.Message = fmt::format("Expected one of '{}' but got '{}'", exp, Token::Translate(token.type));
           descr.Hint = fmt::format("The offending token is '{}'", token.text);
           Error::SyntacticalError(descr);
       }
   }



 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  virtual int lex(void);
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

extern void reflex_code_INITIAL(reflex::Matcher&);

int Lexer::lex(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
{ push(Token::Specifier::Eof); return 0;}
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule Hyc.l:186: \s+ :
            break;
          case 2: // rule Hyc.l:187: "//"[^\n]* :
            break;
          case 3: // rule Hyc.l:188: [$][^$]*[$] :
            break;
          case 4: // rule Hyc.l:189: {kw_return} :
{ push(Token::Specifier::KwReturn);}
            break;
          case 5: // rule Hyc.l:190: {kw_for} :
{ push(Token::Specifier::KwFor);}
            break;
          case 6: // rule Hyc.l:191: {kw_while} :
{ push(Token::Specifier::KwWhile);}
            break;
          case 7: // rule Hyc.l:192: {kw_if} :
{ push(Token::Specifier::KwIf);}
            break;
          case 8: // rule Hyc.l:193: {kw_elif} :
{ push(Token::Specifier::KwElif);}
            break;
          case 9: // rule Hyc.l:194: {kw_else} :
{ push(Token::Specifier::KwElse);}
            break;
          case 10: // rule Hyc.l:195: {kw_struct} :
{ push(Token::Specifier::KwStruct);}
            break;
          case 11: // rule Hyc.l:196: {kw_continue} :
{ push(Token::Specifier::KwContinue);}
            break;
          case 12: // rule Hyc.l:197: {kw_fptr} :
{ push(Token::Specifier::KwFptr);}
            break;
          case 13: // rule Hyc.l:198: {kw_as} :
{ push(Token::Specifier::KwAs);}
            break;
          case 14: // rule Hyc.l:199: {kw_throw} :
{ PUSH(KwThrow);}
            break;
          case 15: // rule Hyc.l:200: {kw_union} :
{ PUSH(KwUnion);}
            break;
          case 16: // rule Hyc.l:201: {kw_namespace} :
{PUSH(KwNamespace);}
            break;
          case 17: // rule Hyc.l:202: {kw_match} :
{PUSH(KwMatch);}
            break;
          case 18: // rule Hyc.l:203: {kw_case} :
{PUSH(KwCase);}
            break;
          case 19: // rule Hyc.l:204: {kw_operator} :
{PUSH(KwOperator);}
            break;
          case 20: // rule Hyc.l:205: {kw_auto} :
{PUSH(KwAuto);}
            break;
          case 21: // rule Hyc.l:206: {kw_del} :
{PUSH(KwDel);}
            break;
          case 22: // rule Hyc.l:207: {double_colon} :
{ PUSH(DoubleColon);}
            break;
          case 23: // rule Hyc.l:208: {dot_comma} :
{ PUSH(DotComma);}
            break;
          case 24: // rule Hyc.l:209: {mem_acc_comma} :
{ PUSH(MemAccComma);}
            break;
          case 25: // rule Hyc.l:210: {double_plus} :
{ PUSH(DoublePlus);}
            break;
          case 26: // rule Hyc.l:211: {double_minus} :
{ PUSH(DoubleMinus);}
            break;
          case 27: // rule Hyc.l:212: {ex_mark} :
{ PUSH(ExclMark);}
            break;
          case 28: // rule Hyc.l:213: {double_qm} :
{ PUSH(DoubleQM);}
            break;
          case 29: // rule Hyc.l:214: {double_em} :
{ PUSH(DoubleEM);}
            break;
          case 30: // rule Hyc.l:215: {tilde} :
{ PUSH(Tilde);}
            break;
          case 31: // rule Hyc.l:216: {gen_fcall_open} :
{ PUSH(GenFCallOpen);}
            break;
          case 32: // rule Hyc.l:217: {gen_fcall_close} :
{PUSH(GenFCallClose);}
            break;
          case 33: // rule Hyc.l:218: {amp} :
{ PUSH(Ampersand);}
            break;
          case 34: // rule Hyc.l:219: {perc} :
{ PUSH(Percent);}
            break;
          case 35: // rule Hyc.l:220: {sr} :
{ PUSH(ShiftRight);}
            break;
          case 36: // rule Hyc.l:221: {sl} :
{ PUSH(ShiftLeft);}
            break;
          case 37: // rule Hyc.l:222: {thrway} :
{ PUSH(ThreeWay);}
            break;
          case 38: // rule Hyc.l:223: {lessEql} :
{ PUSH(LessEql);}
            break;
          case 39: // rule Hyc.l:224: {grEql} :
{ PUSH(GreaterEql);}
            break;
          case 40: // rule Hyc.l:225: {double_eql} :
{ PUSH(DoubleEqual);}
            break;
          case 41: // rule Hyc.l:226: {not_equal} :
{ PUSH(NotEqual);}
            break;
          case 42: // rule Hyc.l:227: {caret} :
{ PUSH(Caret);}
            break;
          case 43: // rule Hyc.l:228: {or} :
{ PUSH(Or);}
            break;
          case 44: // rule Hyc.l:229: {array_start} :
{ PUSH(ArrayStart);}
            break;
          case 45: // rule Hyc.l:230: {array_end} :
{ PUSH(ArrayEnd);}
            break;
          case 46: // rule Hyc.l:231: {hashtag} :
{ PUSH(Hashtag);}
            break;
          case 47: // rule Hyc.l:232: {double_amp} :
{ PUSH(DoubleAmpersand);}
            break;
          case 48: // rule Hyc.l:233: {double_or} :
{ PUSH(DoubleOr);}
            break;
          case 49: // rule Hyc.l:234: {questionmark} :
{ PUSH(QuestionMark);}
            break;
          case 50: // rule Hyc.l:235: {plus_eql} :
{ PUSH(PlusEqual);}
            break;
          case 51: // rule Hyc.l:236: {minus_eql} :
{ PUSH(MinusEqual);}
            break;
          case 52: // rule Hyc.l:237: {asterix_eql} :
{ PUSH(AsterixEqual);}
            break;
          case 53: // rule Hyc.l:238: {slash_eql} :
{ PUSH(SlashEqual);}
            break;
          case 54: // rule Hyc.l:239: {percent_equal} :
{ PUSH(PercentEqual);}
            break;
          case 55: // rule Hyc.l:240: {sl_eql} :
{ PUSH(SlEqual);}
            break;
          case 56: // rule Hyc.l:241: {sr_eql} :
{ PUSH(SrEqual);}
            break;
          case 57: // rule Hyc.l:242: {amp_eql} :
{ PUSH(AmpersandEqual);}
            break;
          case 58: // rule Hyc.l:243: {caret_eql} :
{ PUSH(CaretEqual);}
            break;
          case 59: // rule Hyc.l:244: {or_eql} :
{ PUSH(OrEqual);}
            break;
          case 60: // rule Hyc.l:245: {dot} :
{ PUSH(Dot);}
            break;
          case 61: // rule Hyc.l:246: {mem_acc} :
{ PUSH(MemAccess);}
            break;
          case 62: // rule Hyc.l:247: {comma} :
{ push(Token::Specifier::Comma);}
            break;
          case 63: // rule Hyc.l:248: {rparen_l} :
{ push(Token::Specifier::RParenL);}
            break;
          case 64: // rule Hyc.l:249: {rparen_r} :
{ push(Token::Specifier::RParenR);}
            break;
          case 65: // rule Hyc.l:250: {float} :
{ push(Token::Specifier::Float); }
            break;
          case 66: // rule Hyc.l:251: {double} :
{ push(Token::Specifier::Double); }
            break;
          case 67: // rule Hyc.l:252: {quad} :
{ push(Token::Specifier::Quad); }
            break;
          case 68: // rule Hyc.l:253: {plus} :
{ push(Token::Specifier::Plus); }
            break;
          case 69: // rule Hyc.l:254: {int_} :
{ push(Token::Specifier::Int);}
            break;
          case 70: // rule Hyc.l:255: {uint} :
{ push(Token::Specifier::UInt);}
            break;
          case 71: // rule Hyc.l:256: {half} :
{ push(Token::Specifier::Half);}
            break;
          case 72: // rule Hyc.l:257: {uhalf} :
{ push(Token::Specifier::UHalf);}
            break;
          case 73: // rule Hyc.l:258: {char} :
{ push(Token::Specifier::Char);}
            break;
          case 74: // rule Hyc.l:259: {uchar} :
{ push(Token::Specifier::UChar);}
            break;
          case 75: // rule Hyc.l:260: {short} :
{ push(Token::Specifier::Short);}
            break;
          case 76: // rule Hyc.l:261: {ushort} :
{ push(Token::Specifier::UShort);}
            break;
          case 77: // rule Hyc.l:262: {minus} :
{ push(Token::Specifier::Minus); }
            break;
          case 78: // rule Hyc.l:263: {asterix} :
{ push(Token::Specifier::Asterix); }
            break;
          case 79: // rule Hyc.l:264: {slash} :
{ push(Token::Specifier::Slash); }
            break;
          case 80: // rule Hyc.l:265: {decl_cpy} :
{ push(Token::Specifier::DeclCpy); }
            break;
          case 81: // rule Hyc.l:266: {colon} :
{ push(Token::Specifier::Colon); }
            break;
          case 82: // rule Hyc.l:267: {equal} :
{ push(Token::Specifier::Equal); }
            break;
          case 83: // rule Hyc.l:268: {ident} :
{ push(Token::Specifier::Ident); }
            break;
          case 84: // rule Hyc.l:269: {semicln} :
{ push(Token::Specifier::Semicolon); }
            break;
          case 85: // rule Hyc.l:270: {brace_l} :
{ push(Token::Specifier::BraceL); }
            break;
          case 86: // rule Hyc.l:271: {brace_r} :
{ push(Token::Specifier::BraceR); }
            break;
          case 87: // rule Hyc.l:272: {bracket_r} :
{ push(Token::Specifier::BracketR); }
            break;
          case 88: // rule Hyc.l:273: {bracket_l} :
{ push(Token::Specifier::BracketL);}
            break;
          case 89: // rule Hyc.l:274: {less} :
{ push(Token::Specifier::Less); }
            break;
          case 90: // rule Hyc.l:275: {greater} :
{ push(Token::Specifier::Greater); }
            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c0 = 0, c1 = 0;
  m.FSM_INIT(c1);

S0:
  m.FSM_FIND();
  c1 = m.FSM_CHAR();
  if (c1 == '~') goto S181;
  if (c1 == '}') goto S254;
  if (c1 == '|') goto S195;
  if (c1 == '{') goto S252;
  if (c1 == 'w') goto S69;
  if (c1 == 'u') goto S120;
  if (c1 == 't') goto S113;
  if (c1 == 's') goto S90;
  if (c1 == 'r') goto S54;
  if (c1 == 'o') goto S141;
  if (c1 == 'n') goto S127;
  if (c1 == 'm') goto S134;
  if (c1 == 'i') goto S76;
  if (c1 == 'f') goto S61;
  if (c1 == 'e') goto S83;
  if (c1 == 'd') goto S148;
  if (c1 == 'c') goto S97;
  if ('b' <= c1 && c1 <= 'z') goto S244;
  if (c1 == 'a') goto S105;
  if (c1 == '_') goto S244;
  if (c1 == '^') goto S206;
  if (c1 == ']') goto S256;
  if (c1 == '[') goto S209;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if (c1 == '?') goto S178;
  if (c1 == '>') goto S200;
  if (c1 == '=') goto S203;
  if (c1 == '<') goto S183;
  if (c1 == ';') goto S250;
  if (c1 == ':') goto S155;
  if ('1' <= c1 && c1 <= '9') goto S235;
  if (c1 == '0') goto S223;
  if (c1 == '/') goto S48;
  if (c1 == '.') goto S159;
  if (c1 == '-') goto S165;
  if (c1 == ',') goto S217;
  if (c1 == '+') goto S170;
  if (c1 == '*') goto S214;
  if (c1 == ')') goto S221;
  if (c1 == '(') goto S219;
  if (c1 == '&') goto S188;
  if (c1 == '%') goto S192;
  if (c1 == '$') goto S52;
  if (c1 == '#') goto S212;
  if (c1 == '!') goto S174;
  if (c1 == ' ') goto S258;
  if ('\t' <= c1 && c1 <= '\r') goto S258;
  return m.FSM_HALT(c1);

S48:
  m.FSM_TAKE(79);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S266;
  if (c1 == '/') goto S262;
  return m.FSM_HALT(c1);

S52:
  c1 = m.FSM_CHAR();
  if (c1 == '$') goto S268;
  if (0 <= c1) goto S52;
  return m.FSM_HALT(c1);

S54:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S270;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S61:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'p') goto S284;
  if (c1 == 'o') goto S277;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S69:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'h') goto S291;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S76:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'f') goto S298;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S83:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S304;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S90:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S312;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S97:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S319;
  if ('b' <= c1 && c1 <= 'z') goto S244;
  if (c1 == 'a') goto S326;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S105:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S339;
  if (c1 == 's') goto S333;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S113:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'h') goto S346;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S120:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S353;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S127:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if ('b' <= c1 && c1 <= 'z') goto S244;
  if (c1 == 'a') goto S360;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S134:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if ('b' <= c1 && c1 <= 'z') goto S244;
  if (c1 == 'a') goto S367;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S141:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'p') goto S374;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S148:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S381;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S155:
  m.FSM_TAKE(81);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S390;
  if (c1 == ':') goto S388;
  return m.FSM_HALT(c1);

S159:
  m.FSM_TAKE(60);
  c1 = m.FSM_CHAR();
  if (c1 == ']') goto S396;
  if (c1 == '>') goto S394;
  if ('0' <= c1 && c1 <= '9') goto S398;
  if (c1 == ',') goto S392;
  return m.FSM_HALT(c1);

S165:
  m.FSM_TAKE(77);
  c1 = m.FSM_CHAR();
  if (c1 == '>') goto S405;
  if (c1 == '=') goto S410;
  if (c1 == '-') goto S408;
  return m.FSM_HALT(c1);

S170:
  m.FSM_TAKE(68);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S414;
  if (c1 == '+') goto S412;
  return m.FSM_HALT(c1);

S174:
  m.FSM_TAKE(27);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S418;
  if (c1 == '!') goto S416;
  return m.FSM_HALT(c1);

S178:
  m.FSM_TAKE(49);
  c1 = m.FSM_CHAR();
  if (c1 == '?') goto S420;
  return m.FSM_HALT(c1);

S181:
  m.FSM_TAKE(30);
  return m.FSM_HALT();

S183:
  m.FSM_TAKE(89);
  c1 = m.FSM_CHAR();
  if (c1 == '|') goto S424;
  if (c1 == '=') goto S427;
  if (c1 == '.') goto S422;
  return m.FSM_HALT(c1);

S188:
  m.FSM_TAKE(33);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S432;
  if (c1 == '&') goto S430;
  return m.FSM_HALT(c1);

S192:
  m.FSM_TAKE(34);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S434;
  return m.FSM_HALT(c1);

S195:
  m.FSM_TAKE(43);
  c1 = m.FSM_CHAR();
  if (c1 == '|') goto S439;
  if (c1 == '>') goto S436;
  if (c1 == '=') goto S441;
  return m.FSM_HALT(c1);

S200:
  m.FSM_TAKE(90);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S443;
  return m.FSM_HALT(c1);

S203:
  m.FSM_TAKE(82);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S445;
  return m.FSM_HALT(c1);

S206:
  m.FSM_TAKE(42);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S447;
  return m.FSM_HALT(c1);

S209:
  m.FSM_TAKE(88);
  c1 = m.FSM_CHAR();
  if (c1 == '.') goto S449;
  return m.FSM_HALT(c1);

S212:
  m.FSM_TAKE(46);
  return m.FSM_HALT();

S214:
  m.FSM_TAKE(78);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S451;
  return m.FSM_HALT(c1);

S217:
  m.FSM_TAKE(62);
  return m.FSM_HALT();

S219:
  m.FSM_TAKE(63);
  return m.FSM_HALT();

S221:
  m.FSM_TAKE(64);
  return m.FSM_HALT();

S223:
  m.FSM_TAKE(69);
  c1 = m.FSM_CHAR();
  if (c1 == 'x') goto S455;
  if (c1 == 'u') goto S464;
  if (c1 == 's') goto S473;
  if (c1 == 'i') goto S488;
  if (c1 == 'h') goto S469;
  if (c1 == 'c') goto S471;
  if (c1 == 'b') goto S462;
  if ('8' <= c1 && c1 <= '9') goto S475;
  if ('0' <= c1 && c1 <= '7') goto S478;
  if (c1 == '.') goto S453;
  return m.FSM_HALT(c1);

S235:
  m.FSM_TAKE(69);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S464;
  if (c1 == 's') goto S473;
  if (c1 == 'i') goto S488;
  if (c1 == 'h') goto S469;
  if (c1 == 'c') goto S471;
  if ('0' <= c1 && c1 <= '9') goto S235;
  if (c1 == '.') goto S453;
  return m.FSM_HALT(c1);

S244:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S250:
  m.FSM_TAKE(84);
  return m.FSM_HALT();

S252:
  m.FSM_TAKE(85);
  return m.FSM_HALT();

S254:
  m.FSM_TAKE(86);
  return m.FSM_HALT();

S256:
  m.FSM_TAKE(87);
  return m.FSM_HALT();

S258:
  m.FSM_TAKE(1);
  c1 = m.FSM_CHAR();
  if (c1 == ' ') goto S258;
  if ('\t' <= c1 && c1 <= '\r') goto S258;
  return m.FSM_HALT(c1);

S262:
  m.FSM_TAKE(2);
  c1 = m.FSM_CHAR();
  if ('\v' <= c1) goto S262;
  if ('\n' <= c1) return m.FSM_HALT(c1);
  if (0 <= c1 && c1 <= '\t') goto S262;
  return m.FSM_HALT(c1);

S266:
  m.FSM_TAKE(53);
  return m.FSM_HALT();

S268:
  m.FSM_TAKE(3);
  return m.FSM_HALT();

S270:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S494;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S277:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S501;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S284:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S507;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S291:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S514;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S298:
  m.FSM_TAKE(7);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S304:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S528;
  if (c1 == 'i') goto S521;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S312:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S535;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S319:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S542;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S326:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S549;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S333:
  m.FSM_TAKE(13);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S339:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S556;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S346:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S563;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S353:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S570;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S360:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'm') goto S577;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S367:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S584;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S374:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S591;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S381:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S598;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S388:
  m.FSM_TAKE(22);
  return m.FSM_HALT();

S390:
  m.FSM_TAKE(80);
  return m.FSM_HALT();

S392:
  m.FSM_TAKE(23);
  return m.FSM_HALT();

S394:
  m.FSM_TAKE(32);
  return m.FSM_HALT();

S396:
  m.FSM_TAKE(45);
  return m.FSM_HALT();

S398:
  m.FSM_TAKE(66);
  c1 = m.FSM_CHAR();
  if (c1 == 'q') goto S606;
  if (c1 == 'f') goto S604;
  if (c1 == 'e') goto S608;
  if (c1 == 'E') goto S608;
  if ('0' <= c1 && c1 <= '9') goto S398;
  return m.FSM_HALT(c1);

S405:
  m.FSM_TAKE(61);
  c1 = m.FSM_CHAR();
  if (c1 == ',') goto S611;
  return m.FSM_HALT(c1);

S408:
  m.FSM_TAKE(26);
  return m.FSM_HALT();

S410:
  m.FSM_TAKE(51);
  return m.FSM_HALT();

S412:
  m.FSM_TAKE(25);
  return m.FSM_HALT();

S414:
  m.FSM_TAKE(50);
  return m.FSM_HALT();

S416:
  m.FSM_TAKE(29);
  return m.FSM_HALT();

S418:
  m.FSM_TAKE(41);
  return m.FSM_HALT();

S420:
  m.FSM_TAKE(28);
  return m.FSM_HALT();

S422:
  m.FSM_TAKE(31);
  return m.FSM_HALT();

S424:
  m.FSM_TAKE(36);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S613;
  return m.FSM_HALT(c1);

S427:
  m.FSM_TAKE(38);
  c1 = m.FSM_CHAR();
  if (c1 == '>') goto S615;
  return m.FSM_HALT(c1);

S430:
  m.FSM_TAKE(47);
  return m.FSM_HALT();

S432:
  m.FSM_TAKE(57);
  return m.FSM_HALT();

S434:
  m.FSM_TAKE(54);
  return m.FSM_HALT();

S436:
  m.FSM_TAKE(35);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S617;
  return m.FSM_HALT(c1);

S439:
  m.FSM_TAKE(48);
  return m.FSM_HALT();

S441:
  m.FSM_TAKE(59);
  return m.FSM_HALT();

S443:
  m.FSM_TAKE(39);
  return m.FSM_HALT();

S445:
  m.FSM_TAKE(40);
  return m.FSM_HALT();

S447:
  m.FSM_TAKE(58);
  return m.FSM_HALT();

S449:
  m.FSM_TAKE(44);
  return m.FSM_HALT();

S451:
  m.FSM_TAKE(52);
  return m.FSM_HALT();

S453:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S398;
  return m.FSM_HALT(c1);

S455:
  c1 = m.FSM_CHAR();
  if (c1 == 'x') goto S619;
  if (c1 == 't') goto S619;
  if (c1 == 'i') goto S619;
  if (c1 == 'g') goto S619;
  if (c1 == 'd') goto S619;
  if (c1 == ':') goto S619;
  return m.FSM_HALT(c1);

S462:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '1') goto S630;
  return m.FSM_HALT(c1);

S464:
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S644;
  if (c1 == 'i') goto S638;
  if (c1 == 'h') goto S640;
  if (c1 == 'c') goto S642;
  return m.FSM_HALT(c1);

S469:
  m.FSM_TAKE(71);
  return m.FSM_HALT();

S471:
  m.FSM_TAKE(73);
  return m.FSM_HALT();

S473:
  m.FSM_TAKE(75);
  return m.FSM_HALT();

S475:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S475;
  if (c1 == '.') goto S453;
  return m.FSM_HALT(c1);

S478:
  m.FSM_TAKE(69);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S464;
  if (c1 == 's') goto S473;
  if (c1 == 'i') goto S488;
  if (c1 == 'h') goto S469;
  if (c1 == 'c') goto S471;
  if ('8' <= c1 && c1 <= '9') goto S475;
  if ('0' <= c1 && c1 <= '7') goto S478;
  if (c1 == '.') goto S453;
  return m.FSM_HALT(c1);

S488:
  m.FSM_TAKE(69);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S464;
  if (c1 == 's') goto S473;
  if (c1 == 'h') goto S469;
  if (c1 == 'c') goto S471;
  return m.FSM_HALT(c1);

S494:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S646;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S501:
  m.FSM_TAKE(5);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S507:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S653;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S514:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S659;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S521:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'f') goto S666;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S528:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S672;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S535:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S678;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S542:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S685;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S549:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S692;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S556:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S698;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S563:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S704;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S570:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S711;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S577:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S718;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S584:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'c') goto S725;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S591:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S732;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S598:
  m.FSM_TAKE(21);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S604:
  m.FSM_TAKE(65);
  return m.FSM_HALT();

S606:
  m.FSM_TAKE(67);
  return m.FSM_HALT();

S608:
  c1 = m.FSM_CHAR();
  if (c1 == '-') goto S739;
  if (c1 == '+') goto S739;
  return m.FSM_HALT(c1);

S611:
  m.FSM_TAKE(24);
  return m.FSM_HALT();

S613:
  m.FSM_TAKE(55);
  return m.FSM_HALT();

S615:
  m.FSM_TAKE(37);
  return m.FSM_HALT();

S617:
  m.FSM_TAKE(56);
  return m.FSM_HALT();

S619:
  m.FSM_TAKE(69);
  c1 = m.FSM_CHAR();
  if (c1 == 'x') goto S619;
  if (c1 == 'u') goto S464;
  if (c1 == 't') goto S619;
  if (c1 == 's') goto S473;
  if (c1 == 'h') goto S469;
  if ('g' <= c1 && c1 <= 'i') goto S619;
  if (c1 == 'd') goto S619;
  if (c1 == 'c') goto S471;
  if (c1 == ':') goto S619;
  return m.FSM_HALT(c1);

S630:
  m.FSM_TAKE(69);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S464;
  if (c1 == 's') goto S473;
  if (c1 == 'i') goto S488;
  if (c1 == 'h') goto S469;
  if (c1 == 'c') goto S471;
  if ('0' <= c1 && c1 <= '1') goto S630;
  return m.FSM_HALT(c1);

S638:
  m.FSM_TAKE(70);
  return m.FSM_HALT();

S640:
  m.FSM_TAKE(72);
  return m.FSM_HALT();

S642:
  m.FSM_TAKE(74);
  return m.FSM_HALT();

S644:
  m.FSM_TAKE(76);
  return m.FSM_HALT();

S646:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S741;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S653:
  m.FSM_TAKE(12);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S659:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S748;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S666:
  m.FSM_TAKE(8);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S672:
  m.FSM_TAKE(9);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S678:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'c') goto S754;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S685:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S761;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S692:
  m.FSM_TAKE(18);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S698:
  m.FSM_TAKE(20);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S704:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'w') goto S768;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S711:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S774;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S718:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S780;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S725:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'h') goto S787;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S732:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if ('b' <= c1 && c1 <= 'z') goto S244;
  if (c1 == 'a') goto S793;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S739:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S800;
  return m.FSM_HALT(c1);

S741:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S805;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S748:
  m.FSM_TAKE(6);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S754:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S811;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S761:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S817;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S768:
  m.FSM_TAKE(14);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S774:
  m.FSM_TAKE(15);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S780:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'p') goto S824;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S787:
  m.FSM_TAKE(17);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S793:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S831;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S800:
  m.FSM_TAKE(66);
  c1 = m.FSM_CHAR();
  if (c1 == 'q') goto S606;
  if (c1 == 'f') goto S604;
  if ('0' <= c1 && c1 <= '9') goto S800;
  return m.FSM_HALT(c1);

S805:
  m.FSM_TAKE(4);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S811:
  m.FSM_TAKE(10);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S817:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S838;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S824:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if ('b' <= c1 && c1 <= 'z') goto S244;
  if (c1 == 'a') goto S845;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S831:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S852;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S838:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S859;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S845:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'c') goto S865;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S852:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S872;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S859:
  m.FSM_TAKE(11);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S865:
  m.FSM_TAKE(83);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S878;
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S872:
  m.FSM_TAKE(19);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);

S878:
  m.FSM_TAKE(16);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S244;
  if (c1 == '_') goto S244;
  if ('A' <= c1 && c1 <= 'Z') goto S244;
  if ('0' <= c1 && c1 <= '9') goto S244;
  return m.FSM_HALT(c1);
}

